---
- name: Deploy AMRO app using Helm
  hosts: localhost
  tasks:
    - name: Build backend api Docker image
      command: docker build -t amro-backend-api ./backend_api
    - name: Build data api Docker image
      command: docker build -t amro-data-api ./data_api
    - name: Install backend api to the k8s cluster
      shell: helm install amro-backend-api ./backend_api/charts
    - name: Install data api to the k8s cluster
      shell: helm install amro-data-api ./data_api/charts
    - name: Run health_check.sh script
      script: ./health_check.sh
  